// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCUpFyuWcLnpZqMlPZ7DeIFbhRKDjkmsE',
    appId: '1:246065966215:web:9d48e106a81aa2d4699c22',
    messagingSenderId: '246065966215',
    projectId: 'fir-b5587',
    authDomain: 'fir-b5587.firebaseapp.com',
    storageBucket: 'fir-b5587.firebasestorage.app',
    measurementId: 'G-D11EN03Z7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLkcqRrcAPtewkJ9IkSkfBpnJkV0bZdyQ',
    appId: '1:246065966215:android:561683abe90f3554699c22',
    messagingSenderId: '246065966215',
    projectId: 'fir-b5587',
    storageBucket: 'fir-b5587.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrFvThWiIQJHWIqgzrpZqkj3HsLSMvzOI',
    appId: '1:246065966215:ios:95d8e51daa774f3b699c22',
    messagingSenderId: '246065966215',
    projectId: 'fir-b5587',
    storageBucket: 'fir-b5587.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication33',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrFvThWiIQJHWIqgzrpZqkj3HsLSMvzOI',
    appId: '1:246065966215:ios:95d8e51daa774f3b699c22',
    messagingSenderId: '246065966215',
    projectId: 'fir-b5587',
    storageBucket: 'fir-b5587.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication33',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCUpFyuWcLnpZqMlPZ7DeIFbhRKDjkmsE',
    appId: '1:246065966215:web:c9d4a61a763ba3ff699c22',
    messagingSenderId: '246065966215',
    projectId: 'fir-b5587',
    authDomain: 'fir-b5587.firebaseapp.com',
    storageBucket: 'fir-b5587.firebasestorage.app',
    measurementId: 'G-ENVW40KY1L',
  );

}